#!/bin/zsh

# Up-front dotfiles configuration
# Not part of `load_dotfiles` because it must be sourced before anything else
# to be sure that commands like `brew` (when installed in a custom location)
# are already added to the PATH.
[ -r $HOME/.dotfilesrc ] && source $HOME/.dotfilesrc;

load_dotfiles() {
    declare -a files
    files=(
    #    $HOME/.rvm/scripts/rvm # Load RVM into a shell session *as a function*
    #    $HOME/.travis/travis.sh # Load Travis into a shell session
        $HOME/.dotfiles/shell/options.zsh # Options
        $HOME/.dotfiles/shell/exports.zsh # Exports
        $HOME/.dotfiles/shell/aliases.zsh # Aliases
        $HOME/.dotfiles/shell/functions/* # Functions
        $HOME/.dotfiles/shell/paths.zsh # Path modifications
        #/usr/local/opt/git-extras/share/git-extras/git-extras-completion.zsh
        $HOME/.localrc # Local and private settings not under version control (e.g. git credentials)

    )

    # if these files are readable, source them
    for file in ${(k)files}
    do
        if [[ -r ${file} ]]; then
            source ${file}
        fi
    done
}

load_dotfiles
unset load_dotfiles


### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

### End of Zinit's installer chunk
