#!/bin/zsh

# Up-front dotfiles configuration
# Not part of `load_dotfiles` because it must be sourced before anything else
# to be sure that commands like `brew` (when installed in a custom location)
# are already added to the PATH.
[ -r $HOME/.dotfilesrc ] && source $HOME/.dotfilesrc;

load_dotfiles() {
    declare -a files
    files=(
    #    $HOME/.rvm/scripts/rvm # Load RVM into a shell session *as a function*
    #    $HOME/.travis/travis.sh # Load Travis into a shell session
        $HOME/.dotfiles/shell/paths.zsh # Path modifications
        $HOME/.dotfiles/shell/exports.zsh # Exports
        $HOME/.dotfiles/shell/options.zsh # Options
        $HOME/.dotfiles/shell/aliases.zsh # Aliases
        $HOME/.dotfiles/shell/functions/* # Functions
        #/usr/local/opt/git-extras/share/git-extras/git-extras-completion.zsh
        $HOME/.localrc # Local and private settings not under version control (e.g. git credentials)

    )

    # if these files are readable, source them
    for file in ${(k)files}
    do
        if [[ -r ${file} ]]; then
            source ${file}
        fi
    done
}

load_dotfiles
unset load_dotfiles

# Add zoxide to your shell
# https://github.com/ajeetdsouza/zoxide#step-2-add-zoxide-to-your-shell
compinit
eval "$(zoxide init zsh)"


eval "$(fnm env)"

FNM_USING_LOCAL_VERSION=0

autoload -U add-zsh-hook
_fnm_autoload_hook () {
  if [[ -f .nvmrc && -r .nvmrc || -f .node-version && -r .node-version ]]; then
    FNM_USING_LOCAL_VERSION=1
    fnm use --install-if-missing
  elif [ $FNM_USING_LOCAL_VERSION -eq 1 ]; then
    FNM_USING_LOCAL_VERSION=0
    fnm use --version-file-strategy=recursive --install-if-missing
  fi
}

add-zsh-hook chpwd _fnm_autoload_hook \
    && _fnm_autoload_hook
