#!/bin/bash

run_brew() {
    # Check for Homebrew
    if type_exists 'brew'; then
        e_header "Updating Homebrew..."
        # Use the latest version of Homebrew
        brew update
        [[ $? ]] && e_success "Done"

        e_header "Updating any existing Homebrew formulae..."
        # Upgrade any already-installed formulae
        brew upgrade
        [[ $? ]] && e_success "Done"

        # disable macos apache before install
        sudo apachectl stop
        sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist 2>/dev/null

        if ! formula_exists httpd24; then
            brew install httpd --with-privileged-ports --with-http2
        fi

        e_header "Have launchd start homebrew/apache/httpd24 now and restart at startup"
        sudo brew services start httpd
        [[ $? ]] && e_success "Done"

        #switch from SecureTransport
        if $(brew info curl | grep with-openssl >/dev/null 2>&1); then
            e_success "curl with openssl support already installed."
        else
            e_header "reinstall curl with openssl support"
            brew reinstall --with-openssl curl
            [[ $? ]] && e_success "Done"
        fi

        e_header "Checking status of desired Homebrew formulae..."
        local list_formulae
        local -a missing_formulae
        local -a desired_formulae=(
            # GNU core utilities (those that come with OS X are outdated)
            'coreutils'
            'moreutils'
            'findutils'

            # git
            'git'
            'hub'
            'git-extras'
            'diff-so-fancy'

            # system
            'dnsmasq'
            'libmemcached'
            'libyaml'
            'icu4c'
            'mkcert'
            'nss'

            # shell
            'zsh'
            'bash'
            'bash-completion'
            'tree'
            'ack'
            'gnu-sed --default-names' # Install the GNU version of sed
            'wget --with-iri' # Install wget with IRI support
            'grep'
            'screen'
            'mtr' # mtr - ping & traceroute. best.

            # dev
            'php@5.6'
            'php@7.0'
            'php@7.1'
            'php@7.2'
            'python'
            'node'
            'yarn'
            'mariadb'

            # tools
            'ssh-copy-id'
            'testssl'
            'rsync'
            'rename' # http://plasmasturm.org/code/rename/

            # media
            'ffmpeg --with-libvpx'
            'imagemagick --with-webp'
            'gifsicle'
            'graphicsmagick'
            'optipng'
            'zopfli'
            'jpeg'
            'youtube-dl'
        )

        for index in ${!desired_formulae[*]}
        do
            if ! formula_exists ${desired_formulae[$index]}; then
                # Store the name (and options) of every missing formula
                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")

                e_header "Installing missing Homebrew formulae ${desired_formulae[$index]}"
                brew install ${desired_formulae[$index]}
            fi
        done
        
        # Remove outdated versions from the Cellar
        brew cleanup
    else
        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        exit
    fi

}
