#!/bin/bash

run_help() {

cat <<EOT
OS X dotfiles
Usage: $(basename "$0") [options]
Options:
    -h, --help      Print this help text
    --no-packages   Suppress package updates
    --no-sync       Suppress pulling from the remote repository

Documentation can be found at https://github.com/necolas/dotfiles/
Copyright (c) Nicolas Gallagher
Licensed under the MIT license.
EOT

}