#!/bin/bash

run_postinstall() {

    # Keep-alive: update existing `sudo` time stamp until `we are` has finished
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

    e_header "Have launchd start homebrew/apache/httpd24 now and restart at startup"
    sudo brew services start homebrew/apache/httpd24
    [[ $? ]] && e_success "Done"

    e_header "create a self-signed certificate"
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout $(brew --prefix)/etc/apache2/2.4/server.key -out $(brew --prefix)/etc/apache2/2.4/server.crt
    [[ $? ]] && e_success "Done"

    e_header "Configure apache/httpd24"
    
    apacheConf=$(sudo httpd -V | grep -i server_config_file | cut -d '"' -f 2)

    # load dev modules
    sudo sed -i -e "/LoadModule rewrite_module/s/^#//" $apacheConf && \
    sudo sed -i -e "/LoadModule deflate_module/s/^#//" $apacheConf && \
    sudo sed -i -e "/LoadModule expires_module/s/^#//" $apacheConf && \
    sudo sed -i -e "/LoadModule ssl_module/s/^#//" $apacheConf && \
    sudo sed -i -e "/LoadModule http2_module/s/^#//" $apacheConf && \
    sudo sed -i -e "/LoadModule socache_shmcb_module/s/^#//" $apacheConf && \
    sudo sed -i -e "/LoadModule vhost_alias_module/s/^#//" $apacheConf && \
    sudo sed -i -e "/httpd-ssl.conf/s/^#//" $apacheConf && \
    sudo sed -i -e "/php5_module/s/^#*/#/" $apacheConf && \
    sudo sed -i -e "/php7_module/s/^#//" $apacheConf && \
    sudo sed -i -e "s/DirectoryIndex index.html/DirectoryIndex index.php index.html/g" $apacheConf && \
    sudo sed -i -e "s/User daemon/User _www/g" $apacheConf && \
    sudo sed -i -e "s/Group daemon/Group _www/g" $apacheConf && \
    sudo sed -i -r "s/^Listen 80\d+/Listen 80/g" $apacheConf && \
    mkdir -p /Users/$(whoami)/Sites && \
    sudo sed -i -e "s/\/usr\/local\/var\/www\/htdocs/\/Users\/$(whoami)\/Sites/g" $apacheConf && \
    sudo sed -i -r "s/#ServerName.*/ServerName localhost/" $apacheConf && \
    echo "" >> $apacheConf && \
    echo "<FilesMatch \.php$>" >> $apacheConf && \
    echo "    SetHandler application/x-httpd-php" >> $apacheConf && \
    echo "</FilesMatch>" >> $apacheConf && \
    sudo apachectl -k restart
    [[ $? ]] && e_success "Done"

    e_header "Install php switcher script"
    curl -L https://gist.github.com/w00fz/142b6b19750ea6979137b963df959d11/raw > /usr/local/bin/sphp
    chmod +x /usr/local/bin/sphp

    e_header "Setting up oh-my-zsh..."
    # zsh / oh-my-zsh
    wget --no-check-certificate https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | sh
    # use sindres pure theme
    rsync -avz --quiet ${DOTFILES_DIRECTORY}/shell/pure.zsh-theme  ${HOME}/.oh-my-zsh/custom/pure.zsh-theme
    # set zsh as default shell
    chsh -s `which zsh`
    [[ $? ]] && e_success "Done"

    # https://github.com/jamiew/git-friendly
    # the `push` command which copies the github compare URL to my clipboard is heaven
    bash -c "$(curl -fsSL raw.githubusercontent.com/jamiew/git-friendly/master/install.sh)"

     # allow mtr to run without sudo
    mtrlocation=$(brew info mtr | grep Cellar | sed -e 's/ (.*//') #  e.g. `/Users/paulirish/.homebrew/Cellar/mtr/0.86`
    sudo chmod 4755 $mtrlocation/sbin/mtr
    sudo chown root $mtrlocation/sbin/mtr

    # dnsmasq
    e_header "Setting up dnsmasq..."
    mkdir -pv $(brew --prefix)/etc/ && \
    echo 'address=/.dev/127.0.0.1' >> $(brew --prefix)/etc/dnsmasq.conf && \
    echo 'address=/.work/127.0.0.1' >> $(brew --prefix)/etc/dnsmasq.conf && \
    echo 'address=/.localhost/127.0.0.1' >> $(brew --prefix)/etc/dnsmasq.conf && \
    sudo cp -v $(brew --prefix dnsmasq)/homebrew.mxcl.dnsmasq.plist /Library/LaunchDaemons && \
    sudo launchctl load -w /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist && \
    sudo mkdir -v /etc/resolver && \
    sudo zsh -c 'echo "nameserver 127.0.0.1" > /etc/resolver/dev' && \
    sudo zsh -c 'echo "nameserver 127.0.0.1" > /etc/resolver/work' && \
    sudo zsh -c 'echo "nameserver 127.0.0.1" > /etc/resolver/localhost' && \
    #flush cache
    sudo discoveryutil mdnsflushcache && scutil --dns
    [[ $? ]] && e_success "Done"

    #setup daemon for php 7
    ln -sfv /usr/local/opt/php70/*.plist ~/Library/LaunchAgents && \
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.php70.plist

    # https://rvm.io
    # rvm for the rubiess
    curl -L https://get.rvm.io | bash -s stable --ruby

    # create bin dir
    mkdir -p ${HOME}/bin

    # add DropBox uploader
    curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o ${HOME}/bin/dropbox
    chmod +x ${HOME}/bin/dropbox
    # link key from dropbox if available
    if [ -f ${HOME}/Dropbox/Backup/Macbook/shell/dropbox_uploader ]; then
       ln -s ${HOME}/Dropbox/Backup/Macbook/shell/dropbox_uploader ${HOME}.dropbox_uploader
    fi

    # add wp-cli
    curl "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar" -o ${HOME}/bin/wp
    chmod +x ${HOME}/bin/wp

    # install SpoofMAC
    # https://github.com/feross/SpoofMAC
    pip install SpoofMAC

    # install pygments syntax highlighter
    # http://pygments.org/
    pip install pygments

    # configure diff-so-fancy
    git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"




}
