#!/bin/bash


function localip(){	
	local purple="\x1B\[35m" reset="\x1B\[m"
	networksetup -listallhardwareports | \
		gsed -r "s/Hardware Port: (.*)/\n${purple}\1${reset}/g" | \
		gsed -r "s/Device: (.*)$/ipconfig getifaddr \1/e" | \
		gsed -r "s/^(([0-9]{1,3}\.){3}[0-9]{1,3})$/📶  \1/g" | \
		gsed -r "s/Ethernet Address:/📘 /g" | \
		gsed -r "s/(VLAN Configurations)|==*//g" | \
		grep -A 1 -B 2 '📶'
}