#!/bin/bash

function _localip(){ echo "📶  "$(ipconfig getifaddr "$1"); }

function localip(){

	export -f _localip
	local purple="\x1B\[35m" reset="\x1B\[m"
	networksetup -listallhardwareports | \
		gsed -r "s/Hardware Port: (.*)/${purple}\1${reset}/g" | \
		gsed -r "s/Device: (en.*)$/_localip \1/e" | \
		gsed -r "s/Ethernet Address:/📘 /g" | \
		gsed -r "s/(VLAN Configurations)|==*//g"
}