#!/bin/bash


# Header logging
_header() {
    printf "\n$(tput setaf 7)%s$(tput sgr0)" "$@"
}

# Success logging
_success() {
    printf "  $(tput setaf 64)✓ %s$(tput sgr0)" "$@"
}

# switch from php5 to php7 and vice versa
use-php() {
	# Ask for the administrator password upfront
	sudo -v

  if [[ -n "$1" ]]; then
    _header "Switching cli version"
    php-version "$1"
    [[ $? ]] && _success
  	_header "Updating httpd.conf"
    [[ $? ]] && _success
	sudo sed -i -E -- "s/LoadModule php([0-9]+)_module\s+\/usr/#LoadModule php\1_module \/usr/g" /usr/local/etc/apache2/2.4/httpd.conf
	sudo sed -i -E -- "s/#+LoadModule php${1}_module\s+\/usr/LoadModule php${1}_module \/usr/g" /usr/local/etc/apache2/2.4/httpd.conf

  #LoadModule php7_module    /usr/local/Cellar/php70/7.0.12_5/libexec/apache2/libphp7.so
#LoadModule php5_module    /usr/local/Cellar/php56/5.6.29_5/libexec/apache2/libphp5.so
	_header "Verifying apache config"
	apachectl configtest >/dev/null 2>&1
  	[[ $? ]] && _success 
	_header "Restarting apache"
	sudo apachectl restart
  	[[ $? ]] && _success 
  else
	echo "proper usage: phpswitch <version>. "
  fi
}
